### ISSUE TITLE
Fix & Import the !call feature to the main discord

### ISSUE THREAD

**Issue by leeroytm** [TitanTF/TitanTF#21]
## Scope

**Steam ID or Profile**
> STEAM_0:0:78894932

**Type**
What feature is this bug affecting?
> Moderation

**Region**
What region was the server hosted in?
> So far, Orange x1000 is affected. I haven't tried other servers yet.

**IP**
The IP address of the server the bug occurred on.
> `sg.orangex1000.titan.tf:27000` so far.

## Details

**Describe**
> !call submitted doesn't reach #reports in the legacy discord server. 
> Also, this feature hasn't been implemented yet in the main discord.

**To Reproduce**
> Type !call in chat

**Expected Behavior**
> In some servers, !call did not reach #reports in the legacy discord server
> This indicates this feature might be broken.

**Screenshots**
> None 

**Additional Context**
> Reported long ago. @my3t might have forgotten this or deem this as a not-so-important bug.
> or... this feature is underrated and nobody uses it.

**Comment by my3t** [comment]
Fixed.
