### ISSUE TITLE
Multiple Item in Mystery Box bug

### ISSUE THREAD

**Issue by leeroytm** [TitanTF/TitanTF#27]
## Scope

**Steam ID or Profile**
STEAM_0:0:78894932

**Url**
What page of the website is this bug occurring on?
https://titan.tf/market?mysterybox

**Desktop**
Browser [Microsoft Edge]

**Smartphone**
None

## Details

**Describe**
After purchasing a mystery box, it shows a long selection of ```Mystery Box.
Click to reveal the items in the mystery box!```. Clicking them won't reveal anything.

**To Reproduce**
The steps required to reproduce the behavior:
1. https://titan.tf/market?mysterybox
2. Create a new mystery box
3. Select more than 2 items
4. Create it
5. Buy it back
6. You shouldn't be able to see what you got when clicking them. (as shown in the Screenshot below)

**Expected Behavior**
Items will still receive, just don't know what the player got

**Screenshots**
![unknown](https://user-images.githubusercontent.com/51069447/122678637-35e33f00-d21a-11eb-84c4-00ad5e0b0aef.png)

**Additional Context**
None

**Comment by my3t** [comment]
Resolved.
