### ISSUE TITLE
Servers List

### ISSUE THREAD

**Issue by my3t** [TitanTF/TitanTF#48]
Since the Sep 17 TF2 update, multiple features have broke. The website including SourceBans is unable to query for server information such as the server name, player count, and map name.

Our servers list on the website is currently thinking that all servers are down. You may still find our servers using the "titan" tag in the in-game community server browser.

**Comment by leeroytm** [comment]
Myst has resolved this issue on 22 September
Ref: http://twitter.com/titan_tf/status/1440661023246086147
