### ISSUE TITLE
Legendary REMs and Dispenser Themes Not Playing

### ISSUE THREAD

**Issue by my3t** [TitanTF/TitanTF#57]
A long running bug causing legendary REMs and Dispenser Themes to not play.

**Comment by leeroytm** [comment]
REM not playing has been a bug for while. OR that we haven't heard it for a while.
For Dispenser Themes, I can hear my On Little Cat Feet theme but it is low volume because I set it that way.

**Comment by Lecubon1** [comment]
The Case goes deeper than i thought, more or less complicated
the only clues i had is the server are preventing the theme from playing
probably if im right or wrong but that was i see the theme plays when the server are freezing

**Comment by my3t** [comment]
Legendary Dispenser Themes have been fixed.

**Comment by my3t** [comment]
REMs fixed.
