### ISSUE TITLE
Using !light does not remove the glowing dust on respawn

### ISSUE THREAD

**Issue by jiaweing** [TitanTF/TitanTF#75]
### Steam ID or Profile

NA

### Server IP

All

### What Happened?

After using a glowing dust consumable, the glow retains across deaths. This can be removed with the /light command, but it does not work.

### Rules of Conduct

- [X] I agree to the rules of conduct

**Comment by my3t** [comment]
Resolved.

**Comment by my3t** [comment]
> The Glowing dust item always reapplies itself upon respawn this is what i've thought about

Nope, when they type /light it will stop appearing.
