### ISSUE TITLE
Add a rule to not allow abusing vote system

### ISSUE THREAD

**Issue by leeroytm** [TitanTF/TitanTF#79]
### Discussed in https://github.com/TitanTF/TitanTF/discussions/45

<div type='discussions-op-text'>

<sup>Originally posted by **RoonMoonlight** July 27, 2021</sup>
We got 2 players who were false banned from TitanTF by someone who abused the vote system(GameVoting plugin).

To stop these situation to be happened, we should add the rule to stop player from abusing vote system.

My rule addition suggestion is like this:
---
> ### Community Server
> 4. Do not abuse in-game voting system. (e.g. !votekick, !voteban)</div>

**Comment by my3t** [comment]
Implemented.
