### ISSUE TITLE
On Machine Attack Server The Hitman's Heatmaker causes crashes

### ISSUE THREAD

**Issue by thispirateship** [TitanTF/TitanTF#85]
### Steam ID or Profile

https://steamcommunity.com/id/ThisPirateShip/

### Server IP

209.58.160.137:27000

### What Happened?

Today Im plying on "Titan.TF SG - Machine Attack 1" and I was using sniper with the primary weapon The Hitman's Heatmaker. with full Firing Speed and bullet pershot upgrade while on the weapon Focus ability causes everyone[except me] on the server to disconnected or crashes .

insummary Firing Speed+Bullet Pershot break the weapon.

I suggest blacklisting that weapon.

### Rules of Conduct

- [X] I agree to the rules of conduct

**Comment by my3t** [comment]
Is this confirmed? Could you replicate the steps again and see if it crashes again? It's highly unlikely bullets crash the servers, it's usually projectiles.

**Comment by thispirateship** [comment]
hi sorry for the super late reply. Yes i can replicate them but it didt actually crashes the server, more like crashes the other player that currently playing at that time.
